
import { AppTheme, AppLanguage } from './types';

export const THEME_CONFIG: Record<AppTheme, any> = {
  blue: { primary: 'bg-blue-600', hover: 'hover:bg-blue-700', text: 'text-blue-600', border: 'border-blue-200', gradient: 'from-blue-600 to-blue-400', sidebar: 'bg-blue-900' },
  pink: { primary: 'bg-pink-500', hover: 'hover:bg-pink-600', text: 'text-pink-500', border: 'border-pink-200', gradient: 'from-pink-500 to-rose-400', sidebar: 'bg-pink-900' },
  green: { primary: 'bg-emerald-500', hover: 'hover:bg-emerald-600', text: 'text-emerald-500', border: 'border-emerald-200', gradient: 'from-emerald-500 to-teal-400', sidebar: 'bg-emerald-900' },
  red: { primary: 'bg-red-600', hover: 'hover:bg-red-700', text: 'text-red-600', border: 'border-red-200', gradient: 'from-red-600 to-orange-500', sidebar: 'bg-red-900' },
  black: { primary: 'bg-neutral-800', hover: 'hover:bg-neutral-900', text: 'text-neutral-800', border: 'border-neutral-300', gradient: 'from-neutral-800 to-neutral-600', sidebar: 'bg-neutral-950' },
  night: { primary: 'bg-slate-900', hover: 'hover:bg-slate-800', text: 'text-white', border: 'border-slate-700', gradient: 'from-slate-900 to-indigo-900', sidebar: 'bg-black' }
};

export const TRANSLATIONS = {
  pt: {
    loginTitle: "Toda a sua vida sob controle, em um só lugar.",
    nickname: "email ou @",
    nicknamePlaceholder: "Crie seu @ único",
    password: "Senha",
    email: "Email",
    login: "Entrar",
    register: "Cadastrar",
    createAccount: "Criar conta",
    haveAccount: "Já tem uma conta? Entre aqui",
    noAccount: "Não tem uma conta? Cadastre-se",
    orWith: "Ou entrar com",
    home: "Home",
    focus: "Precisa de mais foco?",
    work: "Meu trabalho",
    college: "Minha faculdade",
    reading: "Minhas leituras",
    training: "Meus treinos",
    media: "Meus filmes/séries",
    finances: "Minhas finanças",
    goals: "Minhas metas gerais",
    diet: "Minha dieta",
    ideas: "Minhas ideias",
    travel: "Minhas viagens",
    studies: "Meus estudos gerais",
    devotional: "Meus devocionais",
    commitments: "Meus compromissos gerais",
    health: "Minha saúde",
    leisure: "Meu lazer",
    marriage: "Meu casamento",
    relationship: "Meus relacionamentos",
    habits: "Monitor de hábitos",
    tutorial: "Tutorial e comandos",
    trash: "Lixeira",
    profile: "Meu perfil",
    categories: "Categorias",
    manageCategories: "Gerenciar Categorias",
    mainTitle: "Respire fundo e mantenha o foco",
    defaultQuote: "Apressa-te em viver bem e pensa que cada dia é, por si só, uma vida.",
    priorities: "Prioridades do dia",
    importantDates: "Datas importantes",
    notepad: "Bloco de notas",
    overview: "Visão geral",
    whatsapp: "Compromissos por Whatsapp",
    pomodoro: "Pomodoro",
    changeTheme: "Mudar Tema",
    changeLang: "Change to English",
    day: "Dia",
    week: "Semana",
    month: "Mês",
    year: "Ano",
    tasks: "Tarefas",
    goalsTable: "Tabela de Metas",
    notebook: "Caderno",
    archived: "Arquivadas",
    download: "Baixar",
    share: "Compartilhar",
    bible: "Bíblia Sagrada NVI",
    subscription: "Assinatura",
    plans: "Planos de Acesso",
    freeTrial: "Período de Teste Gratuito",
    daysRemaining: "dias restantes",
    trialEnded: "Seu teste acabou",
    choosePlan: "Escolha um plano para continuar sua jornada de organização.",
    planMonthly: "Plano Mensal",
    planSemestral: "Plano Semestral",
    planAnnual: "Plano Anual",
    bestValue: "Melhor Valor",
    priceMonthly: "R$ 6,90/mês",
    priceSemestral: "R$ 19,90/6 meses",
    priceAnnual: "R$ 29,90/ano",
    subscribeNow: "Assinar Agora",
    cancelAnytime: "Cancele a qualquer momento",
    autoRenew: "Renovação automática",
    activePlan: "Plano Ativo",
    personalData: "Dados Pessoais",
    accountSettings: "Configurações da Conta",
    siteSettings: "Configurações do Site",
    policy: "Política e Termos",
    closeAccount: "Encerrar Conta",
    confirmClose: "Tem certeza que deseja encerrar sua conta? Todos os dados serão perdidos.",
    membershipSince: "Membro desde",
    editProfile: "Editar Perfil",
    saveChanges: "Salvar Alterações"
  },
  en: {
    loginTitle: "All your life under control, in one place.",
    nickname: "email or @",
    nicknamePlaceholder: "Create your unique @",
    password: "Password",
    email: "Email",
    login: "Login",
    register: "Register",
    createAccount: "Create account",
    haveAccount: "Already have an account? Login here",
    noAccount: "Don't have an account? Register",
    orWith: "Or login with",
    home: "Home",
    focus: "Need more focus?",
    work: "My work",
    college: "My college",
    reading: "My readings",
    training: "My workouts",
    media: "My movies/series",
    finances: "My finances",
    goals: "My general goals",
    diet: "My diet",
    ideas: "My ideas",
    travel: "My travels",
    studies: "My general studies",
    devotional: "My devotionals",
    commitments: "My general commitments",
    health: "My health",
    leisure: "My leisure",
    marriage: "My marriage",
    relationship: "My relationships",
    habits: "Habit tracker",
    tutorial: "Tutorial and commands",
    trash: "Trash",
    profile: "My Profile",
    categories: "Categories",
    manageCategories: "Manage Categories",
    mainTitle: "Breathe deep and stay focused",
    defaultQuote: "Hurry to live well and think that each day is, in itself, a life.",
    priorities: "Daily Priorities",
    importantDates: "Important Dates",
    notepad: "Notepad",
    overview: "Overview",
    whatsapp: "WhatsApp Commitments",
    pomodoro: "Pomodoro",
    changeTheme: "Change Theme",
    changeLang: "Mudar para Português",
    day: "Day",
    week: "Week",
    month: "Month",
    year: "Year",
    tasks: "Tasks",
    goalsTable: "Goals Table",
    notebook: "Notebook",
    archived: "Archived",
    download: "Download",
    share: "Share",
    bible: "Holy Bible NIV",
    subscription: "Subscription",
    plans: "Access Plans",
    freeTrial: "Free Trial Period",
    daysRemaining: "days remaining",
    trialEnded: "Trial has ended",
    choosePlan: "Choose a plan to continue your organization journey.",
    planMonthly: "Monthly Plan",
    planSemestral: "Semestral Plan",
    planAnnual: "Annual Plan",
    bestValue: "Best Value",
    priceMonthly: "R$ 6.90/mo",
    priceSemestral: "R$ 19.90/6 mo",
    priceAnnual: "R$ 29.90/yr",
    subscribeNow: "Subscribe Now",
    cancelAnytime: "Cancel anytime",
    autoRenew: "Auto-renewing",
    activePlan: "Active Plan",
    personalData: "Personal Data",
    accountSettings: "Account Settings",
    siteSettings: "Site Settings",
    policy: "Policy & Terms",
    closeAccount: "Close Account",
    confirmClose: "Are you sure you want to close your account? All data will be lost.",
    membershipSince: "Member since",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes"
  }
};
